"use strict";

const CACHE_KEY = {
  SYSTEM_CONFIG: "SYSTEM_CONFIG",
  EXCHANGE_DATA: "EXCHANGE_DATA",
  NEWS_DATA: "NEWS_DATA",
  AVATAR_LIST: "AVATAR_LIST",
  MARKET_LATEST_RECEIVED_DATETIME: "MARKET_LATEST_RECEIVED_DATETIME",
};

module.exports = {
  CACHE_KEY,
};
